### PR TITLE
Make RequestResponse object to allow custom status code, status text and headers.

### PR DESCRIPTION
**Pull request by dvarchev**
Currently there isn't a way to define responce status code, status text and headers when usign RespondWith method on RequestResponse object.

### CODE REVIEW

**Comment by ataranto** [comment]
Thanks, this looks good. I haven't had much time for CefSharp recently but I will merge this when I get a chance.

**Comment by ataranto** [comment]
i tried to cherry pick 7f0ff5bf8ed2aaa4e8a4d493078db0ae7e01cd19 but it didn't merge cleanly. my commit is here: https://github.com/ataranto/CefSharp/commit/205ba7e4123919bbb81d212c2427c63c62c2b512

thanks!

**Comment by dvarchev** [comment]
I may have messed some things - formatting (tabs) is one thing I regularly miss to check. I'm available, in case you need any assistance.

**Comment by ataranto** [comment]
already merged but forgot to use git commit -c. i gave you credit in the ChangeLog.md though ;-)

**Pull request closed without merging**
