### PR TITLE
Hi

### PR DESCRIPTION
**Pull request by cherpake**
Hi I have added couple of methods to the Utils.cpp in order to translate native objects (structs, arrays) to JS and back.

### CODE REVIEW

**Comment by ataranto** [comment]
hi cherpake,

i don't want to pull in unecessary .h files into include/

Can you send me another pull request without these additions? Also, please note that i just updated my CefSharp fork to build against CEF r291.

Thanks,

--Anthony

**Comment by cherpake** [comment]
I will create another fork from most recent commit and then send a
poll request, how that sounds?

Sent from my iPhone

On 20 בספט 2011, at 16:29, anthony
reply@reply.github.com
wrote:

**Comment by ataranto** [comment]
that sounds perfect, thanks.

**Comment by cherpake** [comment]
## LinkedIn

I'd like to add you to my professional network on LinkedIn.
- Evgeny

Evgeny Cherpak
Senior Windows developer at Cloud Engines
Israel

Confirm that you know Evgeny Cherpak:
https://www.linkedin.com/e/-x1g783-h0xnimey-67/isd/6649573675/dBQ_ByTn/?hs=false&tok=30_3G9j-OCjRc1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/-x1g783-h0xnimey-67/AuRC5_LVQqmNv9BQ3IMnZmPZbQHBv0i90c0hStw2qjw_F9jNT0yhPLatQywDk3P9P3Jh0nOpmqubzAPxSP-ATv66QzTcvT09eS_M_D3/goo/reply%2Bi-1689615-1f8f9a6a3d51a3f1556d7b37d3278077dd2e51a8%40reply%2Egithub%2Ecom/20061/I2302705932_1/?hs=false&tok=2fPonD5maCjRc1

(c) 2012 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.

**Pull request closed without merging**
