### PR TITLE
Added support for exposing CLR properties to Javascript

### PR DESCRIPTION
**Pull request by perlun**

### CODE REVIEW

**Comment by oconnor663** [comment]
Yay!

**Comment by ataranto** [comment]
this is a super noisy diff. did you change a bunch of indentation? mix spaces/tabs?

**Comment by perlun** [comment]
Ah, sorry about that @ataranto... I realize there is some noise in there yes (for example in commit https://github.com/perlun/CefSharp/commit/ca972559c9963f6612f28a4829fe33a58785257c).

It seems like the VS2008-based code base is written with spaces (like I normally do in other projects as well). I guess VS2012 has its default C++ indentation set to tabs, and I have reformatted some files... My apologies. I will change to spaces and reindent the files in question (TypeUtil.cpp, BindingHandler.cpp and possibly some others) to make the diff less noisy, so that you can see the real changes more easily...

**Comment by perlun** [comment]
Well, it got slightly better. Still, some of the files were arguably incorrectly indented before (like WebView.h); it had only one level of indentation rather than two (since it was in the CefSharp.Wpf namespace). I agree this could have been done intentionally to avoid excessive indentation, but it's still a slightly bad idea since it makes it harder to reformat the file (which I feel something you should be able to do without too much fuss).

I suggest you look at the changes with whitespace modifications disabled for the time being (not sure if that can be done here on Github, but a standalone git GUI should be able to let you do it).

Anyway, to make things a little bit easier for you I'll summarize my changes here briefly:
- Upgraded to VS2012 format (the .vcproj to .vcxproj change). Unfortunately, the .sln file diff is noisy; for whatever reason, I couldn't manage to get my Git client to revert the changes at some point even though I hadn't yet touched the file. So I had to commit it. Sorry about that. If this is a setting in the .gitattributes file, please let me know. (I use Sourcetree since I'm on a Mac)
- Minor fix: Change the include of stdafx.h to Stdafx.h, since that's what the file is actually called in the filesystem. This is why you're seeing a number of 1-line changes to almost all files in the project. Nonetheless, it feels better to refer to the file with the right casing.
- Added local vcclr.h file (vcclr_local.h), since unfortunately the built-in VS2012 vcclr.h is incompatible with IntelliSense (making it quite hard to use e.g. the nice "auto" keyword). Can give you more details as needed.
- Rearranged and refactored the BindingHelper to be in a separate sub-namespace, in an attempt to make the code slightly easier to understand. Also started using the "auto" keyword in some of the existing code, and generally tried to refactor it to use smaller, more concise methods etc. Nothing really controversial if you ask me (except for maybe the "auto" keyword which I guess some people would dislike).
- Added support for exposing the CLR properties to Javascript (PropertyAccessor.h).

If there's anything you feel should be done differently in all of this, please let me know and we'll hopefully be able to come to an agreement. I'm all open for ideas; I don't do any other C++ programming these days (but very much C#). So this is a quite interesting mix of a hobby & work for me at the moment, refreshing some ancient skills of mine... :)

**Comment by ataranto** [comment]
I don't really have a preference wrt formatting, tabs spaces, etc. I have tried to use the same formatting that was used in the project when I inherited maintainership. I wouldn't be averse to changing the formatting of every file, but I'd prefer to do that, or other things such as changing the Stdafx.h casing as separate commits/PRs.

**Comment by perlun** [comment]
I get your point... It was a separate commit actually, on my own fork, but it was all squashed into the same PR. Sorry about that. I do think you have a bit of understanding of that workflow though (you fix "other stuff" that you notice in the meanwhile, while working on the "real feature" you're implementing). To me, that's how I work every day at work, but that's a slightly different thing since we don't do pull requests etc...

So, all in all, once more sorry about the noise. I will try to be more "to the point" in my future pull requests (yes, there's definitely more coming :) so that it gets easier for you to review the modifications I've done.

**Comment by perlun** [comment]
@ataranto: It might be worthwhile to look at my other PR first (https://github.com/ataranto/CefSharp/pull/53). If we can manage to get that incorporated, it should make this PR (#55) be slightly less noisy.

**Comment by ataranto** [comment]
Agree, but I haven't started using VS2012 yet and VS2012 can't build chromium, so I'm not sure if we want to make it the default for CefSharp.

**Comment by perlun** [comment]
Okay, see your points. (But as I mentioned elsewhere, VS2012 can build chromium - https://groups.google.com/a/chromium.org/forum/?fromgroups=#!topic/chromium-dev/ftnAUIPBP9Y, read the last message in that thread)

If you aren't using VS2012 yet I can understand you're not so keen on pulling that stuff right in. ;) I don't see so much point in using VS2010 though (except for the Chromium point which might be moot), since the lack of C++ intellisense is quite bad and it doesn't feel that future proof anyway.

Please, let me know what you want me to do - I really want to cooperate with you on getting this stuff in. I could backport the properties change to VS2008 but it means a bit of work so I don't want to do it unless it's really necessary. :-)

**Comment by ataranto** [comment]
I agree that VS2008 support has to go, it's probably prevented a lot of people from contributing to CefSharp. VS2010 is still the "official" supported version to build chromium on windows.

**Comment by perlun** [comment]
I did some more changes to this, so that it's now rebased on top of @mwisnicki's excellent work on the vs2012 branch. Will add another feature shortly, PR coming... :)

Btw, do you happen to have any idea of if/when you will be able to review this stuff?

**Comment by ataranto** [comment]
no timeframe. i'm not actively working on CefSharp at this time.

**Comment by perlun** [comment]
No worries. Would you mind if we make an intermediate CefSharp release in the meanwhile? I know I have some stuff I want to bring out, and there may be other people having pending PR:s that could get included also.

**Comment by perlun** [comment]
Closing now since moved into master @ cefsharp/CefSharp.

**Pull request closed without merging**
